version: '3.8'

services:
 
  # django app service
  compflix:
    image: compflix:latest
    container_name: compflix_container
    build: .
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    command: bash -c "python manage.py makemigrations&&python manage.py migrate&&python manage.py runserver 0.0.0.0:8002 "

    restart: always
    environment:
      DJANGO_SUPERUSER_USERNAME: 'besfort'
      DJANGO_SUPERUSER_PASSWORD: 'besfort'
      DJANGO_SUPERUSER_EMAIL: 'bessffort@gmail.com'

 