# Generated by Django 4.0.3 on 2022-03-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
