# Generated by Django 4.0.3 on 2022-03-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_component_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
